Added pylint2 & pyflakes2 and added support for Python2 in pyanalysis.

diff --git a/accessory/shell_ext b/accessory/shell_ext
--- a/accessory/shell_ext
+++ b/accessory/shell_ext
@@ -149,6 +149,7 @@ isBlockFile() { ([ -b "$1" ] && return 0) || return 1; }
 isInPath() { (command -v "$1" && return 0) || return 1; }
 isBuiltin() { (command -V "$1" 2> /dev/null | grep -q -w -i 'builtin') || return $?; }
 isDir() { ([ -d "$1" ] && return 0) || return 1; }
+isEnvAWS() { if [ -n "${AWS_BATCH_CE_NAME:-}" ] || [ -n "${AWS_BATCH_JOB_ID:-}" ] || [ -n "${AWS_EXECUTION_ENV:-}" ] || [ -n "${LAMBDA_RUNTIME_DIR:-}" ]; then return 0; else return 1; fi; }
 isFile() { ([ -f "$1" ] && return 0) || return 1; }
 isFileExecutable() { ([ -x "$1" ] && return 0) || return 1; }
 isFileReadable() { ([ -r "$1" ] && return 0) || return 1; }
@@ -716,6 +717,24 @@ if [ "$PLATFORM" = 'linux' ] || [ "$PLATFORM" = 'cygwin' ]; then
         fi
     }
 fi
+
+fcat() {  # Find an executable script with the given name (without regex) and open it with cat
+    if [ -z "$1" ]; then
+        printf 'ERROR: A parameter is required!\n' >&2
+        printf 'Find an executable script with the given name (without regex) and open it with cat\n' >&2
+    elif [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "-?" ]; then
+        printf 'Find an executable script with the given name (without regex) and open it with cat\n'
+    elif [ -r "$(which "${1}")" ]; then
+        floc="$(which "${1}")"
+        if file -b -L --mime "$floc" | grep -q '^text'; then
+            cat "$floc"
+        else
+            printf 'ERROR: The file is not a plain-text script!\n' >&2
+        fi
+    else
+        printf 'ERROR: The script was not found!\n' >&2
+    fi
+}
 
 finddir() {  # Find a directory with the given name (without regex); searches from CWD if no directory is specified
     if [ -z "$1" ]; then
diff --git a/scripts/pyanalysis b/scripts/pyanalysis
--- a/scripts/pyanalysis
+++ b/scripts/pyanalysis
@@ -53,6 +53,9 @@ for file in "$@"; do
     hashpling="$(head -1 "$file")"
     echo "$hashpling" | grep -v -E -e '#!/.+python[0-9\.]*' > /dev/null && printf '%s: The specified file is not a Python script!\n' "$file" >&2 && continue
 
+    ispy2=0
+    echo "$hashpling" | grep -q -E -e '#!/.+python2.*' && ispy2=1
+
     if [ -x "$(command -v flake8)" ]; then
         printf '======  *FLAKE8*  ======\n'
         flake8 --jobs=1 --max-complexity=10 --exclude='.bzr,CVS,.git,.hg,.svn,.tox,__init__.py,__init__,__pycache__' --ignore='E501,T001' --benchmark --doctests --show-source --statistics --exit-zero "$file" | awk '{ OFS=""; gsub(/^0$/, ""); print $0; }' | awk NF
@@ -60,11 +63,20 @@ for file in "$@"; do
         printf 'flake8: command not found!\n' >&2
     fi
 
-    if [ -x "$(command -v pyflakes3)" ]; then
-        printf '======  *PYFLAKES*  ======\n'
-        pyflakes3 "$file" | awk NF
-    elif [ "$FirstLoopPass" -eq 0 ]; then
-        printf 'pyflakes3: command not found!\n' >&2
+    if [ "$ispy2" -eq 1 ]; then
+        if [ -x "$(command -v pyflakes2)" ]; then
+            printf '======  *PYFLAKES2*  ======\n'
+            pyflakes2 "$file" | awk NF
+        elif [ "$FirstLoopPass" -eq 0 ]; then
+            printf 'pyflakes2: command not found!\n' >&2
+        fi
+    else
+        if [ -x "$(command -v pyflakes3)" ]; then
+            printf '======  *PYFLAKES*  ======\n'
+            pyflakes3 "$file" | awk NF
+        elif [ "$FirstLoopPass" -eq 0 ]; then
+            printf 'pyflakes3: command not found!\n' >&2
+        fi
     fi
 
     if [ -x "$(command -v pycodestyle)" ]; then
@@ -77,11 +89,20 @@ for file in "$@"; do
         printf 'pycodestyle (formerly pep8): command not found!\n' >&2
     fi
 
-    if [ -x "$(command -v pylint3)" ]; then
-        printf '======  *PYLINT*  ======\n'
-        pylint3 --disable='C0301,I0011' --good-names='i,j,k,v,ex,key,Run,val,_' --notes='DEBUG,FINISH,FIX,FIXME,HERE,TODEBUG,TODO,XXX' --msg-template='{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}' --max-module-lines=4096 --max-returns=16 --persistent=n --reports=y "$file" 2>&1 | awk '{ OFS=""; gsub(/^Using config file .+$/, ""); gsub(/^Report$/, ""); gsub(/^======$/, ""); gsub(/^Unable to init server.*/, ""); print $0; }' | awk NF
-    elif [ "$FirstLoopPass" -eq 0 ]; then
-        printf 'pylint3: command not found!\n' >&2
+    if [ "$ispy2" -eq 1 ]; then
+        if [ -x "$(command -v pylint2)" ]; then
+            printf '======  *PYLINT2*  ======\n'
+            pylint2 --disable='C0301,I0011' --good-names='i,j,k,v,ex,key,Run,val,_' --notes='DEBUG,FINISH,FIX,FIXME,HERE,TODEBUG,TODO,XXX' --msg-template='{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}' --max-module-lines=4096 --max-returns=16 --persistent=n --reports=y "$file" 2>&1 | awk '{ OFS=""; gsub(/^Using config file .+$/, ""); gsub(/^Report$/, ""); gsub(/^======$/, ""); gsub(/^Unable to init server.*/, ""); print $0; }' | awk NF
+        elif [ "$FirstLoopPass" -eq 0 ]; then
+            printf 'pylint2: command not found!\n' >&2
+        fi
+    else
+        if [ -x "$(command -v pylint3)" ]; then
+            printf '======  *PYLINT*  ======\n'
+            pylint3 --disable='C0301,I0011' --good-names='i,j,k,v,ex,key,Run,val,_' --notes='DEBUG,FINISH,FIX,FIXME,HERE,TODEBUG,TODO,XXX' --msg-template='{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}' --max-module-lines=4096 --max-returns=16 --persistent=n --reports=y "$file" 2>&1 | awk '{ OFS=""; gsub(/^Using config file .+$/, ""); gsub(/^Report$/, ""); gsub(/^======$/, ""); gsub(/^Unable to init server.*/, ""); print $0; }' | awk NF
+        elif [ "$FirstLoopPass" -eq 0 ]; then
+            printf 'pylint3: command not found!\n' >&2
+        fi
     fi
 
     if [ -x "$(command -v py_directive_checker)" ]; then
@@ -120,7 +141,11 @@ for file in "$@"; do
     fi
 
     printf '======  *PYTHON DOCTEST*  ======\n'
-    python3 -m doctest --option=NORMALIZE_WHITESPACE "$file" 2>&1 | awk '{ gsub(/^Unable to init server.*/, ""); print $0; }' | awk NF
+    if [ "$ispy2" -eq 1 ]; then
+        python2 -m doctest --option=NORMALIZE_WHITESPACE "$file" 2>&1 | awk '{ gsub(/^Unable to init server.*/, ""); print $0; }' | awk NF
+    else
+        python3 -m doctest --option=NORMALIZE_WHITESPACE "$file" 2>&1 | awk '{ gsub(/^Unable to init server.*/, ""); print $0; }' | awk NF
+    fi
 
     if [ -x "$(command -v code-analysis)" ]; then
         code-analysis "$file"
