Added many more files & file-patterns to delete in cleansystem
Signed-off-by: DevynCJohnson <DevynCJohnson@Gmail.com>

diff --git a/scripts/cleansystem b/scripts/cleansystem
--- a/scripts/cleansystem
+++ b/scripts/cleansystem
@@ -4,7 +4,7 @@
 # kate: encoding utf-8; bom off; syntax shell; indent-mode normal; eol unix; replace-tabs on; indent-width 4; tab-width 4; remove-trailing-space on; line-numbers on;
 #' @brief Remove cache, logs, and other unneeded files
 #' @file cleansystem
-#' @version 2018.12.28
+#' @version 2019.03.07
 #' @author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
 #' @copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/
 
@@ -21,7 +21,10 @@ Help() {
     printf '%s\n' 'Example: cleansystem --deep-clean -l  # Perform deep cleaning and remove non-English locales'
     printf '%s\n' 'Options:'
     printf '%s\n' '-h,--help                 Display help info'
-    printf '%s\n' '-d,--deep-clean           Perform deep cleaning (scan system for *.tmp files and more)'
+    printf '%s\n' '-c,--clock                Fix & adjust the clock (system & hardware)'
+    printf '%s\n' '-D,--deep-clean           Perform deep cleaning (scan system for *.tmp files and more)'
+    printf '%s\n' '-d,--doc,--docs           Delete news, readme, changelog, etc. files under /usr/share/doc/'
+    printf '%s\n' '-f,--fixes                Apply various system fixes'
     printf '%s\n' '-l,--locales              Delete all locales except American English (en-US)'
     printf '%s\n' '-m,--mem,--mem-clean      Clean up memory'
     printf '%s\n' '-s,--ssd,--ssd-clean      Discard unused blocks on all mounted SSD storage units (requires fstrim)'
@@ -90,13 +93,16 @@ fi
 # GETOPT #
 
 
-GOPT="$(getopt -o dhlmsx --long deep-clean,help,locales,mem,mem-clean,ssd,ssd-clean -- "$@")"
+GOPT="$(getopt -o cDdfhlmsx --long clock,deep-clean,doc,docs,fixes,help,locales,mem,mem-clean,ssd,ssd-clean -- "$@")"
 if [ "$?" != '0' ]; then
     exit 1
 fi
 eval set -- "$GOPT"
 
+apply_fixes=0
+fix_clock=0
 deep_clean=0
+del_docs=0
 del_locales=0
 mem_clean=0
 ssd_clean=0
@@ -108,8 +114,20 @@ while true; do
             Help
             exit 0
         ;;
-        -d|--deep-clean)  # Perform deep cleaning
+        -c|--clock)  # Fix & adjust the clock (system & hardware)
+            fix_clock=1
+            shift
+        ;;
+        -D|--deep-clean)  # Perform deep cleaning
             deep_clean=1
+            shift
+        ;;
+        -d|--doc|--docs)  # Delete news, readme, changelog, etc. files under /usr/share/doc/
+            del_docs=1
+            shift
+        ;;
+        -f|--fixes)  # Apply various system fixes
+            apply_fixes=1
             shift
         ;;
         -l|--locales)  # Delete all locales except American English (en-US)
@@ -145,12 +163,13 @@ done
 
 # Cache, Cookies, History, Logs, Temporary Files, & Thumbnails
 
-RM_DIRS="${HOME}/.adobe/Acrobat/*/Cache/${HOME}/.adobe/Flash_Player/AssetCache/${HOME}/.adobe/Flash_Player/NativeCache/${HOME}/.amsn/*/logs/date/${HOME}/.aMule/Temp/${HOME}/.bash_sessions/${HOME}/.beagle/Indexes/${HOME}/.beagle/Log/${HOME}/.beagle/TextCache/${HOME}/.cache/${HOME}/.config/emesene1.0/*/cache/${HOME}/.config/emesene1.0/*/logs/${HOME}/.config/gpodder/cache/${HOME}/.config/libreoffice/*/user/uno_packages/cache/${HOME}/.evolution/cache/${HOME}/.exaile/cache/${HOME}/.exaile/covers/${HOME}/.gftp/cache/${HOME}/.gimp-2*/tmp/${HOME}/.gnome2/rhythmbox/jamendo/${HOME}/.gnome2/rhythmbox/magnatune/${HOME}/.googleearth/Cache/${HOME}/.googleearth/Temp/${HOME}/.hardinfo/${HOME}/.hippo_opensim_viewer/cache/${HOME}/.hippo_opensim_viewer/logs/${HOME}/.icedtea/cache/${HOME}/.icedteaplugin/cache/${HOME}/.java/deployment/cache/${HOME}/.kde/cache-*/${HOME}/.kde4/cache-*/${HOME}/.libreoffice/*/user/config/uno_packages/cache/${HOME}/.libreoffice/*/user/uno_packages/cache/${HOME}/.liferea_*/cache/${HOME}/.liferea_*/mozilla/liferea/Cache/${HOME}/.local/share/zeitgeist/${HOME}/.macromedia/${HOME}/.miro/mozilla/Cache/${HOME}/.nexuiz/data/dlcache/${HOME}/.nv/ComputeCache/${HOME}/.nv/GLCache/${HOME}/.octave_hist${HOME}/.purple/logs/${HOME}/.recoll/xapiandb/${HOME}/.secondlife/cache/${HOME}/.secondlife/logs/${HOME}/.ssr/logs/${HOME}/.warzone2100*/logs/${HOME}/.wine/drive_c/windows/temp/${HOME}/.wine/drive_c/winetrickstmp/${HOME}/.winetrickscache/${HOME}/.xchat2/logs/${HOME}/.xchat2/scrollback/${HOME}/.xchat2/xchatlogs/"
+RM_DIRS="${HOME}/.adobe/Acrobat/*/Cache/${HOME}/.adobe/Flash_Player/AssetCache/${HOME}/.adobe/Flash_Player/NativeCache/${HOME}/.amsn/*/logs/date/${HOME}/.aMule/Temp/${HOME}/.bash_sessions/${HOME}/.beagle/Indexes/${HOME}/.beagle/Log/${HOME}/.beagle/TextCache/${HOME}/.cache/${HOME}/.config/emesene1.0/*/cache/${HOME}/.config/emesene1.0/*/logs/${HOME}/.config/gpodder/cache/${HOME}/.config/libreoffice/*/user/uno_packages/cache/${HOME}/.evolution/cache/${HOME}/.exaile/cache/${HOME}/.exaile/covers/${HOME}/.gftp/cache/${HOME}/.gimp-2*/tmp/${HOME}/.gnome2/rhythmbox/jamendo/${HOME}/.gnome2/rhythmbox/magnatune/${HOME}/.googleearth/Cache/${HOME}/.googleearth/Temp/${HOME}/.hardinfo/${HOME}/.hippo_opensim_viewer/cache/${HOME}/.hippo_opensim_viewer/logs/${HOME}/.icedtea/cache/${HOME}/.icedteaplugin/cache/${HOME}/.java/deployment/cache/${HOME}/.kde/cache-*/${HOME}/.kde4/cache-*/${HOME}/.libreoffice/*/user/config/uno_packages/cache/${HOME}/.libreoffice/*/user/uno_packages/cache/${HOME}/.liferea_*/cache/${HOME}/.liferea_*/mozilla/liferea/Cache/${HOME}/.local/share/zeitgeist/${HOME}/.macromedia/${HOME}/.miro/mozilla/Cache/${HOME}/.nexuiz/data/dlcache/${HOME}/.npm/_logs/${HOME}/.nv/ComputeCache/${HOME}/.nv/GLCache/${HOME}/.octave_hist${HOME}/.purple/logs/${HOME}/.recoll/xapiandb/${HOME}/.secondlife/cache/${HOME}/.secondlife/logs/${HOME}/.ssr/logs/${HOME}/.thumbnails/${HOME}/.warzone2100*/logs/${HOME}/.wine/drive_c/windows/temp/${HOME}/.wine/drive_c/winetrickstmp/${HOME}/.winetrickscache/${HOME}/.xchat2/logs/${HOME}/.xchat2/scrollback/${HOME}/.xchat2/xchatlogs/"
 
-RM_FILES="${HOME}/*.log${HOME}/.adobe/Acrobat/*/Preferences/reader_prefs${HOME}/.amsn/*/displaypic/cache/*.dat${HOME}/.amsn/*/displaypic/cache/*.png${HOME}/.amsn/*/logs/*.log${HOME}/.aMule/log*${HOME}/.bash_history${HOME}/.coffee_history${HOME}/.config/audacious/log*${HOME}/.config/easytag/*.history${HOME}/.config/easytag/*.mask${HOME}/.config/emesene2/*/log${HOME}/.config/emesene2/*/log-journal${HOME}/.config/real/rpcookies.txt${HOME}/.config/Screenlets/*.log${HOME}/.config/VirtualBox/*.log${HOME}/.config/VirtualBox/*.log.*${HOME}/.easytag/*.history${HOME}/.easytag/*.mask${HOME}/.easytag/easytag.log${HOME}/.elinks/cookies${HOME}/.elinks/globhist${HOME}/.elinks/gotohist${HOME}/.elinks/searchhist${HOME}/.exaile/exaile.log${HOME}/.gconf/apps/gnome-settings/gnome-panel/%gconf.xml${HOME}/.gconf/apps/gnome-settings/gnome-search-tool/%gconf.xml${HOME}/.gconf/desktop/%gconf.xml${HOME}/.gconf/desktop/gnome/%gconf.xml${HOME}/.gftp/gftp.log${HOME}/.gnome2/gedit-metadata.xml${HOME}/.idlerc/recent-files.lst${HOME}/.kde/share/apps/gwenview/recentfolders/*rc${HOME}/.kde/share/apps/gwenview/recenturls/*rc${HOME}/.kde/share/apps/RecentDocuments/*.desktop${HOME}/.kde4/share/apps/gwenview/recentfolders/*rc${HOME}/.kde4/share/apps/gwenview/recenturls/*rc${HOME}/.kde4/share/apps/RecentDocuments/*.desktop${HOME}/.lesshst${HOME}/.liferea_*/mozilla/liferea/cookies.sqlite${HOME}/.links/links.his${HOME}/.links2/links.his${HOME}/.local/share/gnome-shell/application_state${HOME}/.local/share/gvfs-metadata/*.log${HOME}/.local/share/gvfs-metadata/*.log${HOME}/.local/share/recently-used.xbel${HOME}/.mandelbulb*/files.recent${HOME}/.mc/filepos${HOME}/.mc/history${HOME}/.miro/*log${HOME}/.miro/miro-log*${HOME}/.nautilus/metafiles/*:*.xml${HOME}/.nautilus/saved-session-*${HOME}/.npm/_cacache${HOME}/.ntrc_2/cookies.txt${HOME}/.ntrc_2/history*${HOME}/.python_history${HOME}/.recently-used.xbel${HOME}/.recently-used.xbel.*${HOME}/.sh_history${HOME}/.Skype/*/chatmsg[0-9]*.dbb${HOME}/.Skype/*/chatsync/*/*.dat${HOME}/.sqlite_history${HOME}/.viminfo${HOME}/.wget-hsts${HOME}/.xine/catalog.cache${HOME}/.xsession-errors${HOME}/.xsession-errors.old"
+RM_FILES="${HOME}/*.log${HOME}/.adobe/Acrobat/*/Preferences/reader_prefs${HOME}/.amsn/*/displaypic/cache/*.dat${HOME}/.amsn/*/displaypic/cache/*.png${HOME}/.amsn/*/logs/*.log${HOME}/.aMule/log*${HOME}/.bash_history${HOME}/.coffee_history${HOME}/.config/audacious/log*${HOME}/.config/easytag/*.history${HOME}/.config/easytag/*.mask${HOME}/.config/emesene2/*/log${HOME}/.config/emesene2/*/log-journal${HOME}/.config/real/rpcookies.txt${HOME}/.config/Screenlets/*.log${HOME}/.config/VirtualBox/*.log${HOME}/.config/VirtualBox/*.log.*${HOME}/.easytag/*.history${HOME}/.easytag/*.mask${HOME}/.easytag/easytag.log${HOME}/.elinks/cookies${HOME}/.elinks/globhist${HOME}/.elinks/gotohist${HOME}/.elinks/searchhist${HOME}/.exaile/exaile.log${HOME}/.gconf/apps/gnome-settings/gnome-panel/%gconf.xml${HOME}/.gconf/apps/gnome-settings/gnome-search-tool/%gconf.xml${HOME}/.gconf/desktop/%gconf.xml${HOME}/.gconf/desktop/gnome/%gconf.xml${HOME}/.gftp/gftp.log${HOME}/.gnome2/gedit-metadata.xml${HOME}/.idlerc/recent-files.lst${HOME}/.kde/share/apps/gwenview/recentfolders/*rc${HOME}/.kde/share/apps/gwenview/recenturls/*rc${HOME}/.kde/share/apps/RecentDocuments/*.desktop${HOME}/.kde4/share/apps/gwenview/recentfolders/*rc${HOME}/.kde4/share/apps/gwenview/recenturls/*rc${HOME}/.kde4/share/apps/RecentDocuments/*.desktop${HOME}/.lesshst${HOME}/.liferea_*/mozilla/liferea/cookies.sqlite${HOME}/.links/links.his${HOME}/.links2/links.his${HOME}/.local/share/gnome-shell/application_state${HOME}/.local/share/gvfs-metadata/*.log${HOME}/.local/share/gvfs-metadata/*.log${HOME}/.local/share/recently-used.xbel${HOME}/.mandelbulber_log.txt${HOME}/.mandelbulb*/files.recent${HOME}/.mc/filepos${HOME}/.mc/history${HOME}/.miro/*log${HOME}/.miro/miro-log*${HOME}/.nautilus/metafiles/*:*.xml${HOME}/.nautilus/saved-session-*${HOME}/.node_repl_history${HOME}/.npm/_cacache${HOME}/.ntrc_2/cookies.txt${HOME}/.ntrc_2/history*${HOME}/.python_history${HOME}/.recently-used.xbel${HOME}/.recently-used${HOME}/.recently-used.xbel.*${HOME}/.sh_history${HOME}/.Skype/*/chatmsg[0-9]*.dbb${HOME}/.Skype/*/chatsync/*/*.dat${HOME}/.sqlite_history${HOME}/.tor/Browser/.local/share/recently-used.xbel${HOME}/.viminfo${HOME}/.wget-hsts${HOME}/.wine/winetricks.log${HOME}/.xine/catalog.cache${HOME}/.xsession-errors.old"
 
 rmDirFromList "${RM_DIRS}"
 rmFilesFromList "${RM_FILES}"
+echo '' > "${HOME}/.xsession-errors"
 
 # Web Browser Cache, Logs, History, & More
 
@@ -259,14 +278,14 @@ if [ "$(id -u)" -eq 0 ]; then
     rm -f -r /var/cache/app-info/ /var/cache/flashplugin-installer/ /var/log/* /var/cache/pbuilder/ || true
     rm -f /var/backups/alternatives* /var/backups/apt* /var/backups/dpkg.status* /var/backups/dpkg*.gz || true
     # Package Management
+    [ -f /etc/apt/sources.list.distUpgrade ] && (rm -f /etc/apt/sources.list.distUpgrade || true)
+    [ -d /var/lib/update-notifier/package-data-downloads/partial/ ] && (rm -f /var/lib/update-notifier/package-data-downloads/partial/*.FAILED || true)
+    [ -d /etc/apt/sources.list.d/ ] && (rm -f /etc/apt/sources.list.d/*.distUpgrade /etc/apt/sources.list.d/*.save || true)
     if [ -x "$(command -v apt-get)" ]; then
         apt-get clean
         apt-get check
         apt-get autoremove
         rm -f -r /var/cache/apt-build/ /var/cache/apt-xapian-index/ || true
-        [ -x "$(command -v update-apt-xapian-index)" ] && update-apt-xapian-index --force
-        [ -d /var/lib/update-notifier/package-data-downloads/partial/ ] && rm -f /var/lib/update-notifier/package-data-downloads/partial/*.FAILED
-        [ -d /etc/apt/sources.list.d/ ] && rm -f /etc/apt/sources.list.d/*.distUpgrade /etc/apt/sources.list.d/*.save
     elif [ -x "$(command -v dnf)" ]; then
         dnf clean all
         dnf check
@@ -288,6 +307,9 @@ if [ "$(id -u)" -eq 0 ]; then
         zypper verify
         zypper remove --clean-deps
     fi
+    [ -d /var/cache/apt/archives/partial/ ] && chown -R _apt:root /var/cache/apt/archives/partial/ && chmod -R 770 /var/cache/apt/archives/partial/
+    [ -x "$(command -v update-apt-xapian-index)" ] && update-apt-xapian-index --force
+    [ -x "$(command -v appstreamcli)" ] && appstreamcli refresh-cache > /dev/null
     # Delete Locales
     if [ "$del_locales" -eq 1 ]; then
         [ -d /usr/lib/libreoffice/share/autocorr/ ] && find /usr/lib/libreoffice/share/autocorr/ -regextype awk -regex '.*en\-US.+' -prune -o -type f -regextype awk -regex '.+/.+\.dat' -exec rm -f '{}' + 2> /dev/null &
@@ -297,22 +319,35 @@ if [ "$(id -u)" -eq 0 ]; then
         [ -d /usr/share/man/ ] && find /usr/share/man/ -name '/usr/share/man/' -prune -o -regextype awk -regex '.*/man[1-8]' -prune -o -type d -regextype awk -regex '/usr/share/man/.+' -exec rm -f -r '{}' + 2> /dev/null &
         [ -d /usr/share/cups/locale/ ] && rm -f -r /usr/share/cups/locale/ &
     fi
+    # Delete Copyright Files, ReleaseNotes, etc.
+    if [ "$del_docs" -eq 1 ]; then
+        [ -d /usr/share/doc/util-linux/releases/ ] && rm -f /usr/share/doc/util-linux/releases/*-ReleaseNotes.gz
+        [ -d /usr/share/doc/ ] && rm -f /usr/share/doc/*/AUTHORS.gz /usr/share/doc/*/BUGS.gz /usr/share/doc/*/changelog.Debian.gz /usr/share/doc/*/copyright /usr/share/doc/*/NEWS.Debian.gz /usr/share/doc/*/NEWS.gz /usr/share/doc/*/README /usr/share/doc/*/README.Debian
+    fi
     # Deep Clean
     if [ "$deep_clean" -eq 1 ]; then
-        rmfiles '.+~$' /
-        rmfiles '\.~lock\..*#$' /
-        rmfiles '.*\.[Bb][Aa][Kk]$' /
-        rmfiles '.*\.[Tt][Mm][Pp]$' /
-        rmfiles '.*\.[Ll][Oo][Gg]$' /var/
         rmfiles '.*(\.|_|\-|)history$' /
+        rmfiles '.*\.[Bb][Aa][Kk]$' /
+        rmfiles '.*\.[Ll][Oo][Gg]$' /var/
+        rmfiles '.*\.[Tt][Mm][Pp]$' /
+        rmfiles '.*\.dpkg\-dist$' /
+        rmfiles '.*\.dpkg\-old$' /
         rmfiles '.*\.DS_Store$' /
+        rmfiles '.+~$' /
         rmfiles '[Tt]humbs\.db$' /
+        rmfiles '\.~lock\..*#$' /
+    fi
+    # System Fixes
+    if [ "$apply_fixes" -eq 1 ]; then
+        [ -e /dev/rtc0 ] && chmod +r /dev/rtc0
+        [ -e /dev/uinput ] && chmod +r /dev/uinput
     fi
     # Final Cleanup
     [ -x "$(command -v dmesg)" ] && dmesg -C
     [ -x "$(command -v mandb)" ] && mandb
     [ "$mem_clean" -eq 1 ] && [ -x "$(command -v sync)" ] && (sleep 1 && sync && sleep 2 && echo 3 > /proc/sys/vm/drop_caches)
     [ "$ssd_clean" -eq 1 ] && [ -x "$(command -v fstrim)" ] && fstrim -a -v
+    [ "$fix_clock" -eq 1 ] && [ -x "$(command -v ntpdate)" ] && ntpdate time.nist.gov && ntpdate time.google.com && ntpdate time.google.com && [ -x "$(command -v hwclock)" ] && hwclock --systohc
 fi
 
 
