Added support for Sed in code-formatter

diff --git a/scripts/code-formatter b/scripts/code-formatter
--- a/scripts/code-formatter
+++ b/scripts/code-formatter
@@ -40,6 +40,7 @@ Help() {
     printf '%s\n' '--json         The input file is JSON code (beautify)'
     printf '%s\n' '--jsonm        The input file is JSON code (minify)'
     printf '%s\n' '-p,--py        The input file is Python source code (uses autopep8 & docformatter)'
+    printf '%s\n' '--sed          The input file is SED source code (uses sedsed)'
     printf '%s\n' '--svg          The input file is SVG source code (uses minifyxml & xmllint)'
     printf '%s\n' '-v,--version   Display version'
     printf '%s\n' '-x             Enable additional and more detailed formatting features'
@@ -53,6 +54,7 @@ Help() {
     printf '%s\n' 'json_reformat - Format JSON code'
     printf '%s\n' 'minifyxml - Minify, repair, and format XML code'
     printf '%s\n' 'rmccmt - Remove comments from C/C++ source code'
+    printf '%s\n' 'sedsed - Reformats SED source code'
     printf '%s\n' 'untrigraph - Remove trigraphs from C source code'
 }
 
@@ -63,7 +65,7 @@ rndfname() { date +%Y%m%u%d%H%M%S%s%N; }  # Create a random filename
 # GETOPT #
 
 
-GOPT="$(getopt -o cf:hpv --long csrc,css,decomment,file:,js,json,jsonm,py,script:,svg,version,help -- "$@")"
+GOPT="$(getopt -o cf:hpv --long csrc,css,decomment,file:,js,json,jsonm,py,script:,sed,svg,version,help -- "$@")"
 eval set -- "$GOPT"
 
 _file=''
@@ -226,6 +228,19 @@ while true; do
                 fi
             else
                 printf 'docformatter: command not found!\n' >&2
+                exit 1
+            fi
+            exit 0
+        ;;
+        --sed)  # The input file is sed source code (uses sedsed)
+            if [ -z "$_file" ]; then
+                printf "No file was specified using the '-f' flag!\n" >&2
+                exit 1
+            fi
+            if [ -x "$(command -v sedsed)" ]; then
+                sedsed --indent --prefix '    ' --quiet --file "$_file"
+            else
+                printf 'sedsed: command not found!\n' >&2
                 exit 1
             fi
             exit 0
