Minor bug fixes & new scripts.

diff --git a/scripts/code-analysis b/scripts/code-analysis
--- a/scripts/code-analysis
+++ b/scripts/code-analysis
@@ -70,6 +70,36 @@ for file in "$@"; do
     [ -x "$(command -v cloc)" ] && cloc --by-file --by-percent cmb --skip-uniqueness --quiet "$file" | awk 'NR > 2 && NF'
     [ -x "$(command -v wc)" ] && printf 'Lines\tWords\tChars\tBytes\tMax-Line-Len\tFilename\n' && wc --bytes --chars --lines --max-line-length --words "$file" | awk '{ gsub(/  /, " "); gsub(/  /, " "); gsub(/ /, "\t"); gsub(/\t\.\//, "\t\t\x2e\x2f"); gsub(/\t\//, "\t\t\x2f"); gsub(/^\t/, ""); print $0; }'
 
+    if [ -x "$(command -v isutf8)" ]; then
+        printf '======  *ISUTF8*  ======\n'
+        isutf8 -l "$file"
+    elif [ "$FirstLoopPass" -eq 0 ]; then
+        printf 'isutf8: command not found!\n' >&2
+    fi
+
+    if [ -x "$(command -v pathchk)" ]; then
+        printf '======  *PATHCHK*  ======\n'
+        pathchk --portability "$file"
+    elif [ "$FirstLoopPass" -eq 0 ]; then
+        printf 'pathchk: command not found!\n' >&2
+    fi
+
+    if [ -x "$(command -v doschk)" ]; then
+        printf '======  *DOSCHK*  ======\n'
+        echo "$file" | doschk
+    elif [ "$FirstLoopPass" -eq 0 ]; then
+        printf 'doschk: command not found!\n' >&2
+    fi
+
+    if [ -x "$(command -v namecheck)" ]; then
+        if [ -n "${NAMECHECK:-}" ]; then
+            printf '======  *NAMECHECK*  ======\n'
+            namecheck "$file"
+        fi
+    elif [ "$FirstLoopPass" -eq 0 ]; then
+        printf 'namecheck: command not found!\n' >&2
+    fi
+
     FirstLoopPass=1
 
 done
diff --git a/scripts/code-formatter b/scripts/code-formatter
--- a/scripts/code-formatter
+++ b/scripts/code-formatter
@@ -12,6 +12,7 @@
 # SETUP #
 
 
+DECOMMENT=0
 EXTRA_PARAMS=0
 version=2018.08.23
 
@@ -32,6 +33,7 @@ Help() {
     printf '%s\n%s\n%s\n' 'Wrapper for prettifiers, minifiers, and auto-formatters' 'Usage: code-formatter [parameters]' 'WARNING: Changes occur in-place'
     printf '%s\n' 'Options:'
     printf '%s\n' '-c,--csrc      The input file is C source code (uses astyle)'
+    printf '%s\n' '--decomment    Remove comments from source code'
     printf '%s\n' '-h,--help      Display help info'
     printf '%s\n' '-p,--py        The input file is Python source code (uses autopep8 & docformatter)'
     printf '%s\n' '--svg          The input file is SVG source code (uses minifyxml & xmllint)'
@@ -40,15 +42,21 @@ Help() {
     printf '\n%s\n' '=====  Tools  ====='
     printf '%s\n' 'astyle - Format C source code'
     printf '%s\n' 'autopep8 - Format Python source code according to the PEP8 standard'
+    printf '%s\n' 'decomment - Remove comments from C/C++ source code'
     printf '%s\n' 'docformatter - Format Python documentation in source code'
     printf '%s\n' 'minifyxml - Minify, repair, and format XML code'
+    printf '%s\n' 'rmccmt - Remove comments from C/C++ source code'
+    printf '%s\n' 'untrigraph - Remove trigraphs from C source code'
 }
+
+
+rndfname() { date +%Y%m%u%d%H%M%S%s%N; }  # Create a random filename
 
 
 # GETOPT #
 
 
-GOPT="$(getopt -o cf:hpv --long csrc,file:,py,script:,svg,version,help -- "$@")"
+GOPT="$(getopt -o cf:hpv --long csrc,decomment,file:,py,script:,svg,version,help -- "$@")"
 eval set -- "$GOPT"
 
 _file=''
@@ -61,7 +69,15 @@ while true; do  # Find input file prior to scanning other parameters
                 printf 'The specified file is non-readable or non-existent!\n' >&2
                 exit 1
             fi
-            break
+            shift 2
+        ;;
+        --decomment)  # Remove comments
+            DECOMMENT=1
+            shift
+        ;;
+        -x)  # Enable extra features
+            EXTRA_PARAMS=1
+            shift
         ;;
         --)  # End
             shift
@@ -71,12 +87,34 @@ while true; do  # Find input file prior to scanning other parameters
     esac
 done
 
+TMP_NAME="$(rndfname)"
+
 eval set -- "$GOPT"
 while true; do
     case "$1" in
         -c|--csrc)  # The input file is C source code (uses astyle)
             if [ -z "$_file" ]; then
                 printf "No file was specified using the '-f' flag!\n" >&2
+                exit 1
+            fi
+            if [ "$DECOMMENT" -eq 1 ]; then
+                if [ -x "$(command -v decomment)" ]; then
+                    decomment "$_file" > "$TMP_NAME"
+                    mv -f "$TMP_NAME" "$_file"
+                elif [ -x "$(command -v rmccmt)" ]; then
+                    rmccmt "$_file" > "$TMP_NAME"
+                    mv -f "$TMP_NAME" "$_file"
+                else
+                    printf 'decomment: command not found!\n' >&2
+                    printf 'rmccmt: command not found!\n' >&2
+                    exit 1
+                fi
+            fi
+            if [ -x "$(command -v untrigraph)" ] && [ "$EXTRA_PARAMS" -eq 1 ]; then
+                untrigraph "$_file" > "$TMP_NAME"
+                mv -f "$TMP_NAME" "$_file"
+            else
+                printf 'untrigraph: command not found!\n' >&2
                 exit 1
             fi
             if [ -x "$(command -v astyle)" ]; then
diff --git a/scripts/cssanalysis b/scripts/cssanalysis
--- a/scripts/cssanalysis
+++ b/scripts/cssanalysis
@@ -2,15 +2,15 @@
 # -*- coding: utf-8-unix; Mode: Shell; indent-tabs-mode: nil; tab-width: 4 -*-
 # vim: set fileencoding=utf-8 filetype=shell syn=sh.doxygen fileformat=unix tabstop=4 expandtab :
 # kate: encoding utf-8; bom off; syntax shell; indent-mode normal; eol unix; replace-tabs on; indent-width 4; tab-width 4; remove-trailing-space on; line-numbers on;
-# @brief Wrapper for scanning XML files (i.e. HTML, MathML, SVG, & more) with various syntax checkers
-# @file xmlanalysis
+# @brief Wrapper for scanning CSS files with various syntax checkers
+# @file cssanalysis
 # @version 2018.08.23
 # @author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
 # @copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/
 
 
 if [ "$1" = '--help' ] || [ "$1" = 'help' ] || [ "$1" = '-h' ]; then
-    printf 'Specify the pathname of each XML file to scan.\n'
+    printf 'Specify the pathname of each CSS file to scan.\n'
     exit 0
 elif [ -z "$1" ]; then
     printf 'ERROR: A parameter is required!\n' >&2
@@ -26,24 +26,12 @@ export FirstLoopPass=0
 
 for file in "$@"; do
     ([ ! -r "$file" ] || [ -d "$file" ]) && printf '%s: The specified file is non-readable or non-existent!\n' "$file" >&2 && continue
-    (head -1 "$file" | grep -v -F -e '<' > /dev/null) && (tail -2 "$file" | grep -v -F -e '>' > /dev/null) && printf '%s: The specified file is not an XML file!\n' "$file" >&2 && continue
 
-    if [ -x "$(command -v weblint)" ] && (head -5 "$file" | grep -F -e '<!DOCTYPE html' > /dev/null); then
-        printf '======  *WEBLINT*  ======\n'
-        weblint --context=1 --fluff --helper --structure "$file"
+    if [ -x "$(command -v csslint)" ]; then
+        printf '======  *CSSLINT*  ======\n'
+        csslint --format=text "$file"
     elif [ "$FirstLoopPass" -eq 0 ]; then
-        printf 'weblint: command not found!\n' >&2
-    fi
-
-    if [ -x "$(command -v xmllint)" ]; then
-        printf '======  *XMLLINT*  ======\n'
-        if (head -5 "$file" | grep -F -e '<!DOCTYPE html' > /dev/null); then
-            xmllint --valid --nowarning --noout --html "$file"
-        else
-            xmllint --valid --nowarning --noout "$file"
-        fi
-    elif [ "$FirstLoopPass" -eq 0 ]; then
-        printf 'xmllint: command not found!\n' >&2
+        printf 'csslint: command not found!\n' >&2
     fi
 
     if [ -x "$(command -v code-analysis)" ]; then
