Fixed some bugs in code-analysis
Signed-off-by: DevynCJohnson <DevynCJohnson@Gmail.com>

diff --git a/scripts/code-analysis b/scripts/code-analysis
--- a/scripts/code-analysis
+++ b/scripts/code-analysis
@@ -57,8 +57,8 @@ for file in "$@"; do
     printf '======  *STATISTICS & FILE INFO*  ======\n'
     if [ "$FirstLoopPass" -eq 0 ]; then
         [ ! -x "$(command -v cloc)" ] && printf 'cloc: command not found!\n' >&2
-        [ ! -x "$(command -v wc)" ] && printf 'wc: command not found!\n' >&2
-        if [ ! -x "$(command -v file)" ]; then
+        [ -z "$(command -v wc)" ] && printf 'wc: command not found!\n' >&2
+        if [ -z "$(command -v file)" ]; then
             printf 'file: command not found!\n' >&2
         elif [ ! -x "$(command -v chardetect)" ]; then
             printf 'chardetect: command not found!\n' >&2
@@ -69,7 +69,7 @@ for file in "$@"; do
         fi
     fi
     ls -a -b -F -h -l "$file"
-    if [ -x "$(command -v file)" ]; then
+    if [ -n "$(command -v file)" ]; then
         file -b -i "$file"
         file -b "$file" | awk_cmd '{ gsub(/^a /, ""); gsub(/^an /, ""); if (NF > 0) { print; } }'
     elif [ -x "$(command -v chardetect)" ]; then
@@ -80,7 +80,7 @@ for file in "$@"; do
         encguess "$file"
     fi
     [ -x "$(command -v cloc)" ] && cloc --by-file --by-percent cmb --skip-uniqueness --quiet "$file" | awk_cmd 'NR > 2 && NF'
-    [ -x "$(command -v wc)" ] && printf 'Lines\tWords\tChars\tBytes\tMax-Line-Len\tFilename\n' && wc --bytes --chars --lines --max-line-length --words "$file" | awk_cmd '{ gsub(/  /, " "); gsub(/  /, " "); gsub(/ /, "\t"); gsub(/\t\.\//, "\t\t\x2e\x2f"); gsub(/\t\//, "\t\t\x2f"); gsub(/^\t/, ""); if (NF > 0) { print; } }'
+    [ -n "$(command -v wc)" ] && printf 'Lines\tWords\tChars\tBytes\tMax-Line-Len\tFilename\n' && wc --bytes --chars --lines --max-line-length --words "$file" | awk_cmd '{ gsub(/  /, " "); gsub(/  /, " "); gsub(/ /, "\t"); gsub(/\t\.\//, "\t\t\x2e\x2f"); gsub(/\t\//, "\t\t\x2f"); gsub(/^\t/, ""); if (NF > 0) { print; } }'
 
     if [ -x "$(command -v isutf8)" ]; then
         printf '======  *ISUTF8*  ======\n'
