Miscellaneous optimizations applied to shell scripts
Signed-off-by: DevynCJohnson <DevynCJohnson@Gmail.com>

diff --git a/scripts/num2hex b/scripts/num2hex
--- a/scripts/num2hex
+++ b/scripts/num2hex
@@ -41,9 +41,9 @@ if [ -x "$(command -v wcalc)" ]; then
     echo "$incoming_data" | wcalc -hex | sed 's|[ \t]*~=[ \t]*||; s|[ \t]*=[ \t]*||' | fmt4pipe | tr '[:lower:]' '[:upper:]' | sed 's|0X|0x|'
 elif [ -x "$(command -v bc)" ]; then
     num="$(echo "obase=16;${incoming_data}" | bc | tr '[:lower:]' '[:upper:]')"
-    printf "0x%s\n" "${num}" | fmt4pipe
+    printf '0x%s\n' "${num}" | fmt4pipe
 elif [ -x "$(command -v python3)" ]; then
     python3 -c "print(hex(${incoming_data}).upper())" | sed 's|0X|0x|' | fmt4pipe
 else
-    printf "0x%X\n" "$incoming_data" | fmt4pipe || printf 'ERROR: No suitable command-line calculator found!\nInstall one of the following: wcalc or bc\n' >&2
+    printf '0x%X\n' "$incoming_data" | fmt4pipe || printf 'ERROR: No suitable command-line calculator found!\nInstall one of the following: wcalc or bc\n' >&2
 fi
diff --git a/scripts/num2oct b/scripts/num2oct
--- a/scripts/num2oct
+++ b/scripts/num2oct
@@ -41,9 +41,9 @@ if [ -x "$(command -v wcalc)" ]; then
     echo "$incoming_data" | wcalc -oct | sed 's|[ \t]*~=[ \t]*||; s|[ \t]*=[ \t]*||' | fmt4pipe
 elif [ -x "$(command -v bc)" ]; then
     num="$(echo "obase=8;${incoming_data}" | bc)"
-    printf "0%s\n" "${num}" | fmt4pipe
+    printf '0%s\n' "${num}" | fmt4pipe
 elif [ -x "$(command -v python3)" ]; then
     python3 -c "print(oct(${incoming_data}))" | fmt4pipe
 else
-    printf "0%o\n" "$incoming_data" | fmt4pipe || printf 'ERROR: No suitable command-line calculator found!\nInstall one of the following: wcalc or bc\n' >&2
+    printf '0%o\n' "$incoming_data" | fmt4pipe || printf 'ERROR: No suitable command-line calculator found!\nInstall one of the following: wcalc or bc\n' >&2
 fi
diff --git a/scripts/oct2num b/scripts/oct2num
--- a/scripts/oct2num
+++ b/scripts/oct2num
@@ -41,10 +41,10 @@ if [ -x "$(command -v wcalc)" ]; then
     echo "$incoming_data" | sed 's|^0||; s|^|0|' | wcalc -dec | sed 's|[ \t]*~=[ \t]*||; s|[ \t]*=[ \t]*||' | fmt4pipe
 elif [ -x "$(command -v bc)" ]; then
     num="$(echo "${incoming_data}" | sed 's|^0||')"
-    printf "%s\n" "$(echo "obase=10;ibase=8;${num}" | bc)" | fmt4pipe
+    printf '%s\n' "$(echo "obase=10;ibase=8;${num}" | bc)" | fmt4pipe
 elif [ -x "$(command -v python3)" ]; then
     num="$(echo "${incoming_data}" | sed 's|^0||; s|^|0|')"
     python3 -c "print(int(${num}))" | fmt4pipe
 else
-    printf "%d\n" "$(echo "${incoming_data}" | sed 's|^0||; s|^|0|')" | fmt4pipe || printf 'ERROR: No suitable command-line calculator found!\nInstall one of the following: wcalc or bc\n' >&2
+    printf '%d\n' "$(echo "${incoming_data}" | sed 's|^0||; s|^|0|')" | fmt4pipe || printf 'ERROR: No suitable command-line calculator found!\nInstall one of the following: wcalc or bc\n' >&2
 fi
