Added bin2hex, bin2num, bin2oct, hex2num, num2bin, num2oct, & oct2num

diff --git a/scripts/oct2num b/scripts/oct2num
--- a/scripts/oct2num
+++ b/scripts/oct2num
@@ -2,8 +2,8 @@
 # -*- coding: utf-8-unix; Mode: Shell; indent-tabs-mode: nil; tab-width: 4 -*-
 # vim: set fileencoding=utf-8 filetype=shell syn=sh.doxygen fileformat=unix tabstop=4 expandtab :
 # kate: encoding utf-8; bom off; syntax shell; indent-mode normal; eol unix; replace-tabs on; indent-width 4; tab-width 4; remove-trailing-space on; line-numbers on;
-#' @brief Get incoming data, pass it to a command-line calculator, and then return the result as hexadecimal
-#' @file num2hex
+#' @brief Get incoming data, pass it to a command-line calculator, and then return the result as a decimal number
+#' @file oct2num
 #' @version 2018.10.14
 #' @author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
 #' @copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/
@@ -38,12 +38,13 @@ fi
 
 
 if [ -x "$(command -v wcalc)" ]; then
-    echo "$incoming_data" | wcalc -hex | sed 's|[ \t]*~=[ \t]*||; s|[ \t]*=[ \t]*||' | fmt4pipe | tr '[:lower:]' '[:upper:]' | sed 's|0X|0x|'
+    echo "$incoming_data" | sed 's|^0||; s|^|0|' | wcalc -dec | sed 's|[ \t]*~=[ \t]*||; s|[ \t]*=[ \t]*||' | fmt4pipe
 elif [ -x "$(command -v bc)" ]; then
-    num="$(echo "obase=16;${incoming_data}" | bc | tr '[:lower:]' '[:upper:]')"
-    printf "0x%s\n" "${num}" | fmt4pipe
+    num="$(echo "${incoming_data}" | sed 's|^0||')"
+    printf "%s\n" "$(echo "obase=10;ibase=8;${num}" | bc)" | fmt4pipe
 elif [ -x "$(command -v python3)" ]; then
-    python3 -c "print(hex(${incoming_data}).upper())" | sed 's|0X|0x|' | fmt4pipe
+    num="$(echo "${incoming_data}" | sed 's|^0||; s|^|0|')"
+    python3 -c "print(int(${num}))" | fmt4pipe
 else
-    printf "0x%X\n" "$incoming_data" | fmt4pipe || printf 'ERROR: No suitable command-line calculator found!\nInstall one of the following: wcalc or bc\n' >&2
+    printf "%d\n" "$(echo "${incoming_data}" | sed 's|^0||; s|^|0|')" | fmt4pipe || printf 'ERROR: No suitable command-line calculator found!\nInstall one of the following: wcalc or bc\n' >&2
 fi
