Added more syntax checkers to phpanalysis
Signed-off-by: DevynCJohnson <DevynCJohnson@Gmail.com>

diff --git a/scripts/phpanalysis b/scripts/phpanalysis
--- a/scripts/phpanalysis
+++ b/scripts/phpanalysis
@@ -4,9 +4,22 @@
 # kate: encoding utf-8; bom off; syntax shell; indent-mode normal; eol unix; replace-tabs on; indent-width 4; tab-width 4; remove-trailing-space on;
 #' @brief Wrapper for scanning PHP files with various syntax checkers
 #' @file phpanalysis
-#' @version 2019.12.31
+#' @version 2020.05.23
 #' @author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
 #' @copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/
+
+# Install Phive:
+# wget -O phive.phar https://phar.io/releases/phive.phar && wget -O phive.phar.asc https://phar.io/releases/phive.phar.asc
+# sudo gpg --keyserver pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79
+# gpg --verify phive.phar.asc phive.phar
+# chmod +x phive.phar && sudo mv phive.phar /usr/local/bin/phive
+
+# Other Optional Dependencies
+# sudo phive install --global dephpend
+# sudo phive install --global phan/phan
+# sudo phive install --global phar.phpunit.de/phpcpd.phar
+# sudo phive install --global phpcpd
+# sudo phive install --global phpstan/phpstan
 
 
 if [ -z "${1:-}" ]; then
@@ -25,6 +38,10 @@ export LANG='en_US.UTF-8'
 export LC_ALL='C'
 export LC_CTYPE='C'
 
+export PHAN_ALLOW_XDEBUG=0
+export PHAN_DISABLE_XDEBUG_WARN=1
+export XDEBUG_CONFIG='profiler_enable=0 remote_autostart=0 remote_enable=0'
+
 
 # SETUP COMMANDS #
 
@@ -34,6 +51,13 @@ if [ -n "$(command -v php)" ]; then
     PHP_EXISTS=1
 else
     printf 'php: command not found!\n' >&2
+fi
+
+PHAN_EXISTS=0
+if [ -n "$(command -v phan)" ]; then
+    PHAN_EXISTS=1
+else
+    printf 'phan: command not found!\n' >&2
 fi
 
 PHPCS_EXISTS=0
@@ -48,6 +72,27 @@ if [ -n "$(command -v phpmd)" ]; then
     PHPMD_EXISTS=1
 else
     printf 'phpmd: command not found!\n' >&2
+fi
+
+PHPSTAN_EXISTS=0
+if [ -n "$(command -v phpstan)" ]; then
+    PHPSTAN_EXISTS=1
+else
+    printf 'phpstan: command not found!\n' >&2
+fi
+
+PHPCPD_EXISTS=0
+if [ -n "$(command -v phpcpd)" ]; then
+    PHPCPD_EXISTS=1
+else
+    printf 'phpcpd: command not found!\n' >&2
+fi
+
+DEPHPEND_EXISTS=0
+if [ -x "$(command -v dephpend)" ]; then
+    DEPHPEND_EXISTS=1
+else
+    printf 'dephpend: command not found!\n' >&2
 fi
 
 CODE_ANALYSIS_EXISTS=0
@@ -78,7 +123,16 @@ fi
 php_sc_func() {
     if [ "$PHP_EXISTS" -eq 1 ]; then
         printf '======  *PHP-SC*  ======\n'
-        php --syntax-check "${1}" | awk_cmd '{ OFS=""; gsub(/^0$/, ""); gsub(/\t/, ":1: "); if (NF > 0) { print; } }'
+        php --syntax-check "${1}" | awk_cmd '{ OFS=""; gsub(/^0$/, ""); gsub(/\t/, ":1: "); gsub(/^No syntax errors detected in .+$/, ""); if (NF > 0) { print; } }'
+    fi
+}
+
+
+#' Run Phan
+phan_func() {
+    if [ "$PHAN_EXISTS" -eq 1 ]; then
+        printf '======  *PHAN*  ======\n'
+        phan --analyze-twice --dead-code-detection --parent-constructor-required --processes=8 --redundant-condition-detection --strict-method-checking --strict-object-checking --strict-param-checking --strict-property-checking --strict-return-checking --unused-variable-detection "${1}" 2>&1 | awk_cmd '{ OFS=""; gsub(/^0$/, ""); gsub(/\t/, ":1: "); gsub(/^░.+$/, ""); gsub(/^Analyzing files.+$/, ""); gsub(/^Analyzing functions.+$/, ""); gsub(/^Parsing files.+$/, ""); gsub(/^Checking for dead code.+$/, ""); gsub(/^\[debug\].+$/, ""); if (NF > 0) { print; } }' | sed -E 's|^(.+)php:([0-9]+) Phan(.+)$|\1php:\2: Phan\3|;'
     fi
 }
 
@@ -87,7 +141,7 @@ php_sc_func() {
 phpcs_func() {
     if [ "$PHPCS_EXISTS" -eq 1 ]; then
         printf '======  *PHPCS*  ======\n'
-        phpcs -d memory_limit=128M -s --report-width=512 --severity=1 --standard=PEAR,PSR2,Zend --exclude=Generic.Commenting.DocComment,Generic.Files.LineLength,Generic.Functions.OpeningFunctionBraceBsdAllman,Generic.WhiteSpace.DisallowTabIndent,PEAR.Commenting.FileComment,PEAR.Commenting.FunctionComment,PEAR.ControlStructures.ControlSignature,PEAR.Functions.FunctionDeclaration,PEAR.WhiteSpace.ScopeClosingBrace,Squiz.Commenting.DocCommentAlignment,Squiz.ControlStructures.ControlSignature,Squiz.Functions.GlobalFunction,Squiz.Functions.MultiLineFunctionDeclaration,Squiz.WhiteSpace.ScopeClosingBrace,Zend.Files.ClosingTag,Zend.NamingConventions.ValidVariableName --tab-width=4 "${1}" | awk_cmd '{ OFS=""; gsub(/^FILE: .+$/, ""); gsub(/^FOUND .+$/, ""); gsub(/^[\-]+$/, ""); gsub(/^0$/, ""); if (NF > 0) { print; } }' | tr '|' ':' | tr '\t' ' ' | sed -E -e 's|  | |g; s|  | |g; s| : |:|g; s|^ ([0-9]+):(.+)|'"${1}"':\1:1:\2|'
+        phpcs -d memory_limit=128M -s --report-width=512 --severity=1 --standard=PEAR,PSR1,PSR12,Zend --exclude=Generic.Commenting.DocComment,Generic.Files.LineLength,Generic.Functions.OpeningFunctionBraceBsdAllman,Generic.WhiteSpace.DisallowTabIndent,PEAR.Commenting.FileComment,PEAR.Commenting.FunctionComment,PEAR.ControlStructures.ControlSignature,PEAR.Functions.FunctionDeclaration,PEAR.WhiteSpace.ScopeClosingBrace,Squiz.Commenting.DocCommentAlignment,Squiz.ControlStructures.ControlSignature,Squiz.Functions.GlobalFunction,Squiz.Functions.MultiLineFunctionDeclaration,Squiz.WhiteSpace.ScopeClosingBrace,Zend.Files.ClosingTag,Zend.NamingConventions.ValidVariableName --tab-width=4 "${1}" | awk_cmd '{ OFS=""; gsub(/^FILE: .+$/, ""); gsub(/^FOUND .+$/, ""); gsub(/^[\-]+$/, ""); gsub(/^0$/, ""); if (NF > 0) { print; } }' | tr '|' ':' | tr '\t' ' ' | sed -E -e 's|  | |g; s|  | |g; s| : |:|g; s|^ ([0-9]+):(.+)|'"${1}"':\1:1:\2|'
     fi
 }
 
@@ -97,6 +151,33 @@ phpmd_func() {
     if [ "$PHPMD_EXISTS" -eq 1 ]; then
         printf '======  *PHPMD*  ======\n'
         phpmd "${1}" text cleancode,codesize,controversial,design,naming,unusedcode | awk_cmd '{ OFS=""; gsub(/^0$/, ""); gsub(/\t/, ":1: "); if (NF > 0) { print; } }'
+    fi
+}
+
+
+#' Run PHP-Stan
+phpstan_func() {
+    if [ "$PHPSTAN_EXISTS" -eq 1 ]; then
+        printf '======  *PHP-STAN*  ======\n'
+        phpstan analyse "${1}" 2>&1 | awk_cmd '{ OFS=""; gsub(/^0$/, ""); gsub(/\t/, ":1: "); gsub(/^.+░░░░░░░░░░░░░░░░░░░░░░░░░░░.+$/, ""); gsub(/^.+▓.+$/, ""); if (NF > 0) { print; } }'
+    fi
+}
+
+
+#' Run PHPCPD
+phpcpd_func() {
+    if [ "$PHPCPD_EXISTS" -eq 1 ]; then
+        printf '======  *PHPCPD*  ======\n'
+        phpcpd --fuzzy "${1}" | awk_cmd '{ OFS=""; gsub(/^0$/, ""); gsub(/\t/, ":1: "); gsub(/^phpcpd .+$/, ""); if (NF > 0) { print; } }'
+    fi
+}
+
+
+#' Run dephpend
+dephpend_func() {
+    if [ "$DEPHPEND_EXISTS" -eq 1 ]; then
+        printf '======  *DEPHPEND*  ======\n'
+        dephpend --quiet text "${1}"
     fi
 }
 
@@ -116,21 +197,35 @@ for file in "$@"; do
     { [ ! -r "$file" ] || [ -d "$file" ]; } && printf '%s: The specified file is non-readable or non-existent!\n' "$file" >&2 && continue
 
     PHP_BUFFER="/tmp/$(uuid).phpanalysis.tmp"
+    PHAN_BUFFER="/tmp/$(uuid).phpanalysis.tmp"
     PHPCS_BUFFER="/tmp/$(uuid).phpanalysis.tmp"
     PHPMD_BUFFER="/tmp/$(uuid).phpanalysis.tmp"
+    PHPSTAN_BUFFER="/tmp/$(uuid).phpanalysis.tmp"
+    PHPCPD_BUFFER="/tmp/$(uuid).phpanalysis.tmp"
+    DEPHPEND_BUFFER="/tmp/$(uuid).phpanalysis.tmp"
     CODE_ANALYSIS_BUFFER="/tmp/$(uuid).phpanalysis.tmp"
 
     php_sc_func "$file" > "${PHP_BUFFER}" &
+    phan_func "$file" > "${PHAN_BUFFER}" &
     phpcs_func "$file" > "${PHPCS_BUFFER}" &
     phpmd_func "$file" > "${PHPMD_BUFFER}" &
+    phpstan_func "$file" > "${PHPSTAN_BUFFER}" &
+    phpcpd_func "$file" > "${PHPCPD_BUFFER}" &
+    dephpend_func "$file" > "${DEPHPEND_BUFFER}" &
     code_analysis_func "$file" > "${CODE_ANALYSIS_BUFFER}" &
 
     wait
 
     printf "%s\\n" "$(cat < "${PHP_BUFFER}")"
     rm -f "${PHP_BUFFER}" || true
+    printf "%s\\n" "$(cat < "${PHAN_BUFFER}")"
+    rm -f "${PHAN_BUFFER}" || true
     printf "%s\\n%s\\n" "$(cat < "${PHPCS_BUFFER}")" "$(cat < "${PHPMD_BUFFER}")"
     rm -f "${PHPCS_BUFFER}" "${PHPMD_BUFFER}" || true
+    printf "%s\\n%s\\n" "$(cat < "${PHPSTAN_BUFFER}")" "$(cat < "${PHPCPD_BUFFER}")"
+    rm -f "${PHPSTAN_BUFFER}" "${PHPCPD_BUFFER}" || true
+    printf "%s\\n" "$(cat < "${DEPHPEND_BUFFER}")"
+    rm -f "${DEPHPEND_BUFFER}" || true
     printf "%s\\n" "$(cat < "${CODE_ANALYSIS_BUFFER}")"
     rm -f "${CODE_ANALYSIS_BUFFER}" || true
 
