Applied various improvements to executable shell scripts

diff --git a/scripts/pyanalysis b/scripts/pyanalysis
--- a/scripts/pyanalysis
+++ b/scripts/pyanalysis
@@ -9,14 +9,14 @@
 #' @copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/
 
 
-if [ "$1" = '--help' ] || [ "$1" = 'help' ] || [ "$1" = '-h' ]; then
+if [ -z "${1:-}" ]; then
+    printf 'ERROR: A parameter is required!\n' >&2
+    exit 1
+elif [ "$1" = '--help' ] || [ "$1" = 'help' ] || [ "$1" = '-h' ]; then
     printf 'Specify the pathname of each Python script to scan.\n'
     exit 0
 elif [ ! -x "$(command -v python3)" ]; then
     printf 'python3: command not found!\n' >&2
-    exit 1
-elif [ -z "$1" ]; then
-    printf 'ERROR: A parameter is required!\n' >&2
     exit 1
 fi
 
@@ -60,7 +60,7 @@ fi
 # MAIN #
 
 
-for file in "$@"; do
+for file in "${@:-}"; do
     ([ ! -r "$file" ] || [ -d "$file" ]) && printf '%s: The specified file is non-readable or non-existent!\n' "$file" >&2 && continue
     hashpling="$(head -1 "$file")"
     echo "$hashpling" | grep -v -E -e '#!/.+python[0-9\.]*' > /dev/null && printf '%s: The specified file is not a Python script!\n' "$file" >&2 && continue
diff --git a/scripts/todo-scanner b/scripts/todo-scanner
--- a/scripts/todo-scanner
+++ b/scripts/todo-scanner
@@ -12,7 +12,10 @@
 # MAIN #
 
 
-if [ "$1" = '--help' ] || [ "$1" = 'help' ] || [ "$1" = '-h' ]; then
+if [ -z "${1:-}" ]; then
+    printf 'ERROR: A parameter is required!\n' >&2
+    exit 1
+elif [ "$1" = '--help' ] || [ "$1" = 'help' ] || [ "$1" = '-h' ]; then
     printf 'Specify the pathname of the directory to scan.\n'
     exit 0
 elif [ -f "$1" ]; then
@@ -21,7 +24,4 @@ elif [ -f "$1" ]; then
 elif [ -d "$1" ]; then
     grep -E -n -H -o -r '(#|<\?\-\-) ([Dd][Ee][Bb][Uu][Gg]|[Ff][Ii][Nn][Ii][Ss][Hh]|[Ff][Ii][Xx]|[Ff][Ii][Xx][Mm][Ee]|[Rr][Ee][Pp][Aa][Ii][Rr]|[Tt][Ee][Ss][Tt][Ii][Nn][Gg]|[Tt][Oo][Dd][Ee][Bb][Uu][Gg]|[Tt][Oo][Dd][Oo]|[Tt][Oo][Mm][Vv]|[Tt][Oo][Rr][Mm]|[Xx][Xx][Xx])[ ]?: .+' "$1"
     exit 0
-elif [ -z "$1" ]; then
-    printf 'ERROR: A parameter is required!\n' >&2
-    exit 1
 fi
diff --git a/scripts/win2unixlines b/scripts/win2unixlines
--- a/scripts/win2unixlines
+++ b/scripts/win2unixlines
@@ -9,16 +9,16 @@
 #' @copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/
 
 
-if [ "$1" = '--help' ] || [ "$1" = 'help' ] || [ "$1" = '-h' ]; then
+if [ -z "${1:-}" ]; then
+    printf 'ERROR: A parameter is required!\n' >&2
+    exit 1
+elif [ "$1" = '--help' ] || [ "$1" = 'help' ] || [ "$1" = '-h' ]; then
     printf '%s\n%s\n%s\n%s\n' \
         'Convert Windows newlines (\r\n) to Unix newlines (\n) using one of the following methods:' \
         ' - Specify the pathname of each file to convert.' \
         ' - Specify the directory of files to convert.' \
         ' - Specify the pathname of each file and directories of files to convert.'
     exit 0
-elif [ -z "$1" ]; then
-    printf 'ERROR: A parameter is required!\n' >&2
-    exit 1
 fi
 
 
