Fixed bugs & improved the code in the analysis & graphing scripts
Signed-off-by: DevynCJohnson <DevynCJohnson@Gmail.com>

diff --git a/scripts/pygraphcalls b/scripts/pygraphcalls
--- a/scripts/pygraphcalls
+++ b/scripts/pygraphcalls
@@ -4,7 +4,7 @@
 # kate: encoding utf-8; bom off; syntax shell; indent-mode normal; eol unix; replace-tabs on; indent-width 4; tab-width 4; remove-trailing-space on;
 #' @brief Graph the calls of a Python2 project
 #' @file pygraphcalls
-#' @version 2019.07.25
+#' @version 2019.07.26
 #' @author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
 #' @copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/
 
@@ -17,6 +17,7 @@ elif [ ! -x "$(command -v dot)" ]; then
     exit 1
 elif [ "${1:-}" = '--help' ] || [ "${1:-}" = '-h' ]; then
     printf 'pygraphcalls DIRECTORY PROJECT_NAME\n'
+    exit 0
 fi
 
 
@@ -29,21 +30,38 @@ elif [ -z "${2:-}" ]; then
 fi
 
 
-save_path="${PWD}"
+fixsvg() {
+    [ -x "$(command -v minifyxml)" ] && find "${HOME}/Diagrams" -type f -name "*.svg" -exec minifyxml --svg --inplace --remove-all-metadata {} \;
+}
 
-cd "${1}" || exit 1
 
-FILES="$(find "${1}" -type f -name "*.py" -not \( -path "*/.bzr/*" -o -path "*/.cvs/*" -o -path "*/.git/*" -o -path "*/.hg/*" -o -path "*/.svn/*" -o -path "*/bin/*" -o -path "*/build/*" -o -path "*/debugging/*" -o -path "*/doc/*" -o -path "*/log/*" -o -path "*/logging/*" -o -path "*/logs/*" -o -path "*/temp/*" -o -path "*/testing/*" -o -path "*/tmp/*" \) -exec printf '%s ' '{}' +)"
-pyan2 "${FILES}" --dot --colored --no-defines --grouped --nested-groups > "${HOME}/${2}.dot"
-
-if [ -f "${HOME}/${2}.dot" ]; then
-    dot -Granksep=1.5 -Tsvg -o "${HOME}/${2}.svg" "${HOME}/${2}.dot"
-    mv "${HOME}/classes.dot" "${HOME}/${2}_Classes.dot"
+[ ! -d "${HOME}/Diagrams" ] && mkdir "${HOME}/Diagrams"
+if [ ! -d "${HOME}/Diagrams" ]; then
+    printf 'Failed to create the "Diagrams" directory!\n' >&2
+    exit 1
 fi
 
-cd "${save_path}" || exit 1
+
+FILES="$(find "${1}" -type f -name "*.py" -not \( -path "*/.bzr/*" -o -path "*/.cvs/*" -o -path "*/.git/*" -o -path "*/.hg/*" -o -path "*/.svk/*" -o -path "*/.svn/*" -o -path "*/bin/*" -o -path "*/build/*" -o -path "*/debugging/*" -o -path "*/doc/*" -o -path "*/log/*" -o -path "*/logging/*" -o -path "*/logs/*" -o -path "*/temp/*" -o -path "*/testing/*" -o -path "*/tmp/*" \) -exec printf '%s ' '{}' +)"
+# shellcheck disable=SC2086
+pyan2 $FILES --dot --colored --grouped --nested-groups > "${HOME}/Diagrams/${2}.dot"
+
+if [ -f "${HOME}/Diagrams/${2}.dot" ]; then
+    dot -q -Gconcentrate=true -Gnewrank=true -Gnodesep=2 -Granksep=2 -Tsvg -x -o "${HOME}/Diagrams/${2}.svg" "${HOME}/Diagrams/${2}.dot" &
+    dot -q -Gnewrank=true -Gnodesep=1 -Goverlap=false -Granksep=2 -Tsvg -x -o "${HOME}/Diagrams/${2}_2.svg" "${HOME}/Diagrams/${2}.dot" &
+    dot -q -Gnewrank=true -Gnodesep=1 -Goverlap=scale -Granksep=2 -Tsvg -x -o "${HOME}/Diagrams/${2}_3.svg" "${HOME}/Diagrams/${2}.dot" &
+    neato -q -Gnewrank=true -Goverlap=false -Gsplines=ortho -Tsvg -x -o "${HOME}/Diagrams/${2}_Spring.svg" "${HOME}/Diagrams/${2}.dot" &
+    neato -q -Gnewrank=true -Goverlap=scale -Gsplines=ortho -Tsvg -x -o "${HOME}/Diagrams/${2}_Spring_2.svg" "${HOME}/Diagrams/${2}.dot" &
+    sfdp -q -Gnewrank=true -Gnodesep=3 -Goverlap=false -Granksep=4 -Gsplines=ortho -Tsvg -x -o "${HOME}/Diagrams/${2}_Undirected.svg" "${HOME}/Diagrams/${2}.dot" &
+    sfdp -q -Gnewrank=true -Gnodesep=1 -Goverlap=scale -Granksep=2 -Gsplines=ortho -Tsvg -x -o "${HOME}/Diagrams/${2}_Undirected_2.svg" "${HOME}/Diagrams/${2}.dot" &
+    twopi -q -Gnewrank=true -Granksep=4 -Tsvg -x -o "${HOME}/Diagrams/${2}_Radial.svg" "${HOME}/Diagrams/${2}.dot" &
+    twopi -q -Gnewrank=true -Goverlap=false -Granksep=2 -Tsvg -x -o "${HOME}/Diagrams/${2}_Radial_2.svg" "${HOME}/Diagrams/${2}.dot" &
+    twopi -q -Gnewrank=true -Goverlap=scale -Granksep=1 -Tsvg -x -o "${HOME}/Diagrams/${2}_Radial_3.svg" "${HOME}/Diagrams/${2}.dot" &
+    wait
+    fixsvg
+fi
 
 
-[ ! -f "${HOME}/${2}.svg" ] && exit 1
+[ ! -f "${HOME}/Diagrams/${2}.svg" ] && exit 1
 
 exit 0
diff --git a/scripts/pygraphimports3 b/scripts/pygraphimports3
--- a/scripts/pygraphimports3
+++ b/scripts/pygraphimports3
@@ -4,7 +4,7 @@
 # kate: encoding utf-8; bom off; syntax shell; indent-mode normal; eol unix; replace-tabs on; indent-width 4; tab-width 4; remove-trailing-space on;
 #' @brief Graph the imports of a Python3 project
 #' @file pygraphimports3
-#' @version 2019.07.25
+#' @version 2019.07.26
 #' @author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
 #' @copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/
 
@@ -14,6 +14,7 @@ if [ ! -x "$(command -v python3)" ]; then
     exit 1
 elif [ "${1:-}" = '--help' ] || [ "${1:-}" = '-h' ]; then
     printf 'pygraphimports3 DIRECTORY MAIN_FILE PROJECT_NAME\npygraphimports3 ./project ./project/main.py My_Project\n'
+    exit 0
 fi
 
 
@@ -29,20 +30,33 @@ elif [ -z "${3:-}" ]; then
 fi
 
 
+[ ! -d "${HOME}/Diagrams" ] && mkdir "${HOME}/Diagrams"
+if [ ! -d "${HOME}/Diagrams" ]; then
+    printf 'Failed to create the "Diagrams" directory!\n' >&2
+    exit 1
+fi
+
+
 save_path="${PWD}"
 
 cd "${1}" || exit 1
 
-python3 -m modulegraph2 --format dot -x _abcoll -x _collections -x _ctypes -x _dummy_thread -x _functools -x _hashlib -x _io -x _ssl -x _subprocess -x _thread -x _warnings -x _weakref -x _weakrefset -x abc -x arrow -x asn1crypto -x bable -x backports -x base64 -x binascii -x boto3 -x botocore -x calendar -x CoffeeScript -x collections -x configparser -x copy_ref -x cPickle -x cpuinfo -x Crypto -x cryptography -x cssmin -x cStringIO -x ctypes -x datetime -x decimal -x doctest -x dummy_threading -x email -x enum -x errno -x fasteners -x flask -x flask_babel -x flask_login -x flask_mail -x flask_restplus -x flask_sqlalchemy -x flask_wtf -x functools -x getopt -x gettext -x hashlib -x heapq -x hmac -x httplib -x inspect -x io -x jinja2 -x json -x jsonpickle -x linecache -x locale -x logging -x M2Crypto -x MarkupSafe -x markupsafe -x math -x mimetools -x multiprocessing -x netaddr -x optparse -x ordereddict -x org -x os -x passlib -x pbr -x pdfkit -x pickle -x pkgutil -x posixpath -x pprint -x psutil -x psycopg2 -x pymongo -x pyOpenSSL -x pytz -x quopri -x random -x re -x redis -x repr -x requests -x s3transfer -x sets -x slimit -x smtplib -x socket -x sqlalchemy -x SQLAlchemy -x SQLAlchemy-Utils -x sqlalchemy_utils -x sqlalchemy_utils.functions.orm -x ssl -x string -x StringIO -x subprocess -x textwrap -x threading -x time -x traceback -x types -x unittest -x urllib -x UserDict -x uu -x uuid -x uWSGI -x warnings -x werkzeug -x wtforms -x WTForms -x xml -x zipimport --path "${1}" --output "${HOME}/${3}_Dependencies.dot" "${2}"
+python3 -m modulegraph2 --format dot -x _abcoll -x _collections -x _ctypes -x _dummy_thread -x _functools -x _hashlib -x _io -x _ssl -x _subprocess -x _thread -x _warnings -x _weakref -x _weakrefset -x abc -x arrow -x asn1crypto -x bable -x backports -x base64 -x binascii -x boto3 -x botocore -x calendar -x CoffeeScript -x collections -x configparser -x copy_ref -x cPickle -x cpuinfo -x Crypto -x cryptography -x cssmin -x cStringIO -x ctypes -x cupy -x datetime -x decimal -x doctest -x dummy_threading -x email -x enum -x errno -x fasteners -x flask -x flask_babel -x flask_login -x flask_mail -x flask_restplus -x flask_sqlalchemy -x flask_wtf -x functools -x getopt -x gettext -x hashlib -x heapq -x hmac -x httplib -x inspect -x io -x jinja2 -x json -x jsonpickle -x linecache -x locale -x logging -x M2Crypto -x MarkupSafe -x markupsafe -x math -x mimetools -x multiprocessing -x netaddr -x numpy -x optparse -x ordereddict -x org -x os -x passlib -x pbr -x pdfkit -x pickle -x pkgutil -x posixpath -x pprint -x psutil -x psycopg2 -x pymongo -x pyOpenSSL -x pytz -x quopri -x random -x re -x redis -x regex -x repr -x requests -x s3transfer -x sets -x slimit -x smtplib -x socket -x sqlalchemy -x SQLAlchemy -x SQLAlchemy-Utils -x sqlalchemy_utils -x sqlalchemy_utils.functions.orm -x ssl -x string -x StringIO -x subprocess -x sys -x textwrap -x threading -x time -x traceback -x types -x unittest -x urllib -x UserDict -x uu -x uuid -x uWSGI -x warnings -x werkzeug -x wtforms -x WTForms -x xml -x zipimport --path "${1}" --output "${HOME}/Diagrams/${3}_Dependencies.dot" "${2}"
 
-if [ -f "${HOME}/${3}_Dependencies.dot" ]; then
-    sed -i 's|MissingModule|ExcludedModule|g' "${HOME}/${3}_Dependencies.dot"
-    dot -Gnodesep=1.4 -Gpenwidth=0.2 -Granksep=2 -Tsvg -o "${HOME}/${3}_Dependencies.svg" "${HOME}/${3}_Dependencies.dot"
+if [ -f "${HOME}/Diagrams/${3}_Dependencies.dot" ]; then
+    sed -i "s|MissingModule|ExcludedModule|g; s|${HOME}/||g" "${HOME}/Diagrams/${3}_Dependencies.dot"
+    dot -Gnewrank=true -Gnodesep=1.4 -Gpenwidth=0.2 -Granksep=2 -Tsvg -x -o "${HOME}/Diagrams/${3}_Dependencies.svg" "${HOME}/Diagrams/${3}_Dependencies.dot" &
+    sfdp -q -Gnewrank=true -Gnodesep=1 -Goverlap=scale -Granksep=2 -Gsplines=ortho -Tsvg -x -o "${HOME}/Diagrams/${3}_Dependencies_Undirected.svg" "${HOME}/Diagrams/${3}_Dependencies.dot" &
+    wait
+    if [ -x "$(command -v minifyxml)" ]; then
+        [ -f "${HOME}/Diagrams/${3}_Dependencies.svg" ] && minifyxml --svg --inplace --remove-all-metadata "${HOME}/Diagrams/${3}_Dependencies.svg"
+        [ -f "${HOME}/Diagrams/${3}_Dependencies_Undirected.svg" ] && minifyxml --svg --inplace --remove-all-metadata "${HOME}/Diagrams/${3}_Dependencies_Undirected.svg"
+    fi
 fi
+
 
 cd "${save_path}" || exit 1
 
-
-[ ! -f "${HOME}/${3}_Dependencies.svg" ] && exit 1
+[ ! -f "${HOME}/Diagrams/${3}_Dependencies.svg" ] && exit 1
 
 exit 0
diff --git a/scripts/pygraphmemusage b/scripts/pygraphmemusage
--- a/scripts/pygraphmemusage
+++ b/scripts/pygraphmemusage
@@ -1,10 +1,10 @@
-#!/bin/sh
+#!/bin/bash
 # -*- coding: utf-8-unix; Mode: Shell; indent-tabs-mode: nil; tab-width: 4 -*-
 # vim: set fileencoding=utf-8 filetype=shell syn=sh.doxygen fileformat=unix tabstop=4 expandtab :
 # kate: encoding utf-8; bom off; syntax shell; indent-mode normal; eol unix; replace-tabs on; indent-width 4; tab-width 4; remove-trailing-space on;
 #' @brief Graph the memory usage of a Python3 program
 #' @file pygraphmemusage
-#' @version 2019.07.25
+#' @version 2019.07.26
 #' @author Devyn Collier Johnson <DevynCJohnson@Gmail.com>
 #' @copyright Public Domain (CC0) - https://creativecommons.org/publicdomain/zero/1.0/
 
@@ -13,7 +13,8 @@ if [ ! -x "$(command -v psrecord)" ]; then
     printf 'psrecord: command not found!\n' >&2
     exit 1
 elif [ "${1:-}" = '--help' ] || [ "${1:-}" = '-h' ]; then
-    printf 'pygraphmemusage PROCESS_NAME CHART_NAME [DURATION_SEC] [COMMAND]\nWhen specifying a command, set duration to "0" if the memory usage should be recorded the entire time\n'
+    printf 'pygraphmemusage PROCESS_NAME CHART_NAME [COMMAND]\nWhen specifying a command, set duration to "0" if the memory usage should be recorded the entire time\n'
+    exit 0
 fi
 
 
@@ -25,24 +26,32 @@ elif [ -z "${2:-}" ]; then
     exit 1
 fi
 
-if [ -n "${3:-}" ] && [ "${3}" != '0' ]; then
-    DURATION="--duration ${3}"
-else
-    DURATION=''
+EXECMD=0
+if [ -n "${3:-}" ]; then
+    tmp_ifs="$IFS"
+    IFS=' '
+    read -ra command_string <<< "$3"
+    [ -n "${command_string:-}" ] && command_name="${command_string[0]}"
+    [ -x "$(command -v "$command_name")" ] && EXECMD=1
+    IFS="$tmp_ifs"
 fi
 
-EXECMD=0
-[ -n "${4:-}" ] && EXECMD=1
+
+[ ! -d "${HOME}/Diagrams" ] && mkdir "${HOME}/Diagrams"
+if [ ! -d "${HOME}/Diagrams" ]; then
+    printf 'Failed to create the "Diagrams" directory!\n' >&2
+    exit 1
+fi
 
 
 if [ "$EXECMD" -eq 1 ]; then
-    psrecord --include-children --interval 1 "${DURATION}" --plot "${HOME}/${2}.png" "${4}"
+    psrecord "${3}" --include-children --interval 0.1 --plot "${HOME}/Diagrams/${2}.png"
 else
     PROCESS_PID="$(pgrep "$1")"
-    [ -n "${PROCESS_PID:-}" ] && psrecord --include-children --interval 1 "${DURATION}" --plot "${HOME}/${2}.png" "$PROCESS_PID"
+    [ -n "${PROCESS_PID:-}" ] && psrecord "$PROCESS_PID" --include-children --interval 0.1 --plot "${HOME}/Diagrams/${2}.png"
 fi
 
 
-[ ! -f "${HOME}/${2}.png" ] && exit 1
+[ ! -f "${HOME}/Diagrams/${2}.png" ] && exit 1
 
 exit 0
